clc;clear;close all
tic;
% ------------- Mesh --------------------
% generated by meshfun.m in tool
load meshdata.mat; % rectangle
%load meshdataCircle.mat;  % circle
figure, showmesh(node,elem);
findnode(node); % findelem(node,elem);

% ---------------- PDE data -----------------------
pde = Poissondata();
bdNeumann = 'abs(x-1)<1e-4 | abs(x-0)<1e-4'; % string for Neumann (rectangle)
%bdNeumann = [];
%bdNeumann = 'y>=0'; % string for Neumann  (circle)
bdStruct = setboundary(node,elem,bdNeumann); 

% ------- Solve the problem -----
u = PoissonVEM(node,elem,pde,bdStruct);

% ------- error analysis ----------
uexact = pde.uexact; ue = uexact(node);
figure,
subplot(1,2,1), showsolution(node,elem,u);  zlabel('u');
subplot(1,2,2), showsolution(node,elem,ue); zlabel('ue');
Eabs = abs(u-ue);
figure,showsolution(node,elem,Eabs); zlim('auto'); zlabel('Err');
format shorte;
Err = norm(Eabs)/norm(ue)
toc







